server:
  port: 8080
spring:
  application:
    name: mybatis-xml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1046
# mybatis 配置
mybatis:
  type-aliases-package: com.chan.mybatis_xml.entities
  configuration:
    map-underscore-to-camel-case: true